### ISSUE TITLE
12 Volt Deep cycle value

### ISSUE THREAD

**Issue by rescuemoe** [zNitche/picoVoltmeter#1]
Hello,
Will this code and resistor set up work for a 12 volt Deep cycle battery
Looking to do something for a battery that is on a battery backup sump pump to alert via Email when it a start to see a change in the voltage that the battery is going bad.
I have the code and everything else for sending out email.
Just need  a way to read the battery once a week to check the status. 
THanks!

**Comment by zNitche** [comment]
Hi @rescuemoe , yes this will work with 12v battery out of the box, however I'd rather pick different pair of resistors, let's say 4k and 1k so we will get 3.3v at ADC pin with 16v source connected, this way your readings will be more accurate, also you should add 3.3v zener diode (in parallel between ADC pin and GND) for extra protection in case of voltage spikes. 

Getting voltage readings using rpi pico may be good for low risk projects (due to adc spikes and possible interference from connected battery load), but if you care most about accuracy, better alternative might be to use dedicated digital voltmeter like DFRobot I2C Digital Wattmete or if you want to get info if battery voltage is below certain threshold you can use TL431 transistor to short circuit Pico 3.3v pin with GPIO pin to get high/low digital signal.

**Comment by rescuemoe** [comment]
Thank you for the info 

Really do not need 100% accurate.
The battery just sits on a trickle charger hooked up to a secondary sup pump. Almost never goes on unless we lose power for an extented period of time.
 Just want to check the state of the battery once a day or ever other day a nd if a see a downward trend I know it is time to replace
Was going to add code so when it reads the battery if it gets a weird reading or a reading that the battery is a bad state it would read it again 2-3 times to check before it sends me an email that I need to inspect the battery

I will look into the DFRobot I2C Digital Wattmeter as well
Thanks for the information

**Comment by zNitche** [comment]
You can always test Pico ADC before getting into i2c wattmeters, and if the results are ok there is no need to buy or search for driver to use separated device. 

Also your approach with performing many readings before making decision if battery is in bad condition might be enough to solve problems I mentioned previously.
